### PR TITLE
Add support for Initiating a request with Chasqui

### PR DESCRIPTION
**Pull request by pelle**

### CODE REVIEW

**Review by c-castillo — CHANGES_REQUESTED** [review]
The scope of changes required are easy to understand. I will just remove the  extra `/v1/api` on the endpoints, and change the URL of the service to `https://api.uport.me/chasqui/` since the feature is gonna be implemented on the lambda version of it.

**Comment by pelle** [comment]
@c-castillo updated the urls

**Review by c-castillo — APPROVED** [review]

**Comment by c-castillo** [comment]
thanks @pelle

**Comment by davidperrenoud** [comment]
Some general remarks:

1. Shouldn't it be `PUT /topic`? You might want to be able to update the JWT if you have the QR code is some permanent form. The DID which signed the JWT should match the DID which signed the new JWT.

1. After the JWT is expired, the server could be allowed to delete the QR code. If a QR code is deleted, it cannot be updated anymore.

1. Shouldn't `GET /topic/:id` answer with status 404 if the QR code is invalid or does not exist anymore?

1. The whole "Receiving a response from client" section -> how the callback is called could be left as an application-dependant detail. You would not want to use polling in production as a way to get in "real time" the data from the callback. And you would certainly want to send a confirmation to the client that the claims were properly sent.

**Pull request merged**
